# 空氣污染監測網 網路爬蟲實作練習


* 能夠利用 selenium + BeautifulSoup 撰寫爬蟲，並存放到合適的資料結構

## 作業目標

根據範例 ，完成以下問題：

* ① 取出 台北市士林區 2018/01 – 2018/08 的 SO2 資料
* ② 取出 台北市士林區 2018/01 – 2018/08 的 SO2、CO 資料

### ① 取出 台北市士林區 2018/01 – 2018/08 的 SO2 資料

In [18]:
from selenium import webdriver
from selenium.webdriver.support.ui import Select
from bs4 import BeautifulSoup
from selenium.webdriver.chrome.options import Options
import time
chrome_options = Options()
chrome_options.add_argument('--headless')
chrome_options.add_argument('--no-sandbox')
chrome_options.add_argument('--disable-dev-shm-usage')
chrome_options.add_argument('--disable-gpu')
browser = webdriver.Chrome(executable_path='./chromedriver',options=chrome_options)

browser.get("http://taqm.epa.gov.tw/taqm/tw/MonthlyAverage.aspx")
selectYear = Select(browser.find_element_by_id("ctl05_ddlYear"))
selectYear.select_by_value('2018')

browser.find_element_by_id('ctl05_btnQuery').click()
time.sleep(3)
html_source = browser.page_source

soup = BeautifulSoup(html_source, 'html.parser')
table = soup.find('table', class_='TABLE_G')
#print(table)

count = 0
td = {}
temp = ""
temp2 = ""
for i in table.find_all('td'):
    if i.get_attribute_list("style")[0] == 'white-space:nowrap;':
        if temp != "":
            break
        td[i.text] = {}
        temp = i.text
    if i.get_attribute_list("valign")[0] == 'top':
        continue
    if "/" in i.text:
        if temp2 == "2018/08":
            break
        temp2 = i.text
    else:
        if i.text.strip() != "":
            td[temp][temp2] = i.text
        else:
            continue

browser.quit()
import pandas as pd
pd.DataFrame(td)

          SO2
2018/01  1.80
2018/02  1.90
2018/03  2.20
2018/04  2.30
2018/05  3.10
2018/06  2.70
2018/07  2.20
2018/08  2.40

### ② 取出 台北市士林區 2018/01 – 2018/08 的 SO2、CO 資料

In [21]:
from selenium import webdriver
from selenium.webdriver.support.ui import Select
from bs4 import BeautifulSoup
from selenium.webdriver.chrome.options import Options
import time
chrome_options = Options()
chrome_options.add_argument('--headless')
chrome_options.add_argument('--no-sandbox')
chrome_options.add_argument('--disable-dev-shm-usage')
chrome_options.add_argument('--disable-gpu')
browser = webdriver.Chrome(executable_path='./chromedriver',options=chrome_options)

browser.get("http://taqm.epa.gov.tw/taqm/tw/MonthlyAverage.aspx")
selectYear = Select(browser.find_element_by_id("ctl05_ddlYear"))
selectYear.select_by_value('2018')

browser.find_element_by_id('ctl05_btnQuery').click()
time.sleep(3)
html_source = browser.page_source

soup = BeautifulSoup(html_source, 'html.parser')
table = soup.find('table', class_='TABLE_G')
#print(table)

count = 0
td = {}
temp = ""
temp2 = ""
for i in table.find_all('td'):
    if i.get_attribute_list("style")[0] == 'white-space:nowrap;':
        td[i.text] = {}
        temp = i.text
    if i.get_attribute_list("valign")[0] == 'top':
        continue
    if "/" in i.text:
        if temp2 == "2018/08" and temp == "CO":
            break
        temp2 = i.text
    else:
        if i.text.strip() != "" and temp2 not in ['2018/09','2018/10','2018/11','2018/12']:
            td[temp][temp2] = i.text
        else:
            continue

browser.quit()
import pandas as pd
pd.DataFrame(td)

          SO2    CO
2018/01  1.80  0.34
2018/02  1.90  0.44
2018/03  2.20  0.40
2018/04  2.30  0.38
2018/05  3.10  0.34
2018/06  2.70  0.29
2018/07  2.20  0.21
2018/08  2.40  0.30